djangoProject/PersonCenter/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView
urlpatterns = [
    path('getUserName/', views.get_username),
    path('personCenter/', views.personCenter),
    path('personDetail/', views.personDetail),
    path('changePassword/', views.changePassword),
    path('deleteUser/', views.deleteUser),
    path('getHeadSculpturePath/', views.get_headSculpturePath),
    path('uploadAvatar/', views.uploadAvatar),
]

djangoProject/TaskManage/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView
urlpatterns = [
    path('publishTask/', views.publishTask),
    path('publish_task/', views.publish_task, name='publish_task'),
    path('get_tasks_list/', views.get_tasks_list, name='get_tasks_list'),
    path('getMyTasksList/', views.myPublishedTasks),
    path('get_task_details/', views.get_task_details, name='get_task_details'),
    path('modifyTask/', views.modifyTask, name='modifyTask'),
    path('delete_task/', views.delete_task, name='delete_task'),
    ##0529更新 by zcg

    path('search_tasks/', views.search_tasks, name='search_tasks'),
    path('search_results/', views.search_results, name='search_results'),
    path('task/<int:task_id>/', views.task_detail, name='task_detail'),
    path('task_list/', views.task_list),
    path('homepageforannotator/',views.homepage_annotator)
]

djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from RegisterLogin import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.index, name='index'),
    path('index', views.index),#0529新加入
    path('register1/', views.register1),
    path('register2/', views.register2),
    path('login/', views.login),
    path('homePublisher/', views.homePublisher),
    path('homeAnnotator/', views.homeAnnotator),
    path('homeAdmin/', views.homeAdmin, name='homeAdmin'),
    path('approve_user/<int:user_id>/', views.approve_user, name='approve_user'),
    path('task/', include('TaskManage.urls')),
    path('personCenter/', include('PersonCenter.urls')),
    path('OrderManage/', include("OrderManage.urls")),
    path('AnnotationMethod/', include("AnnotationMethod.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject/DataAnnodationSystem/models.py
from django.db import models

class Admin(models.Model):
    userID = models.CharField(max_length=20, primary_key=True)
    password = models.CharField(max_length=100)

class User(models.Model):
    PERMISSION_CHOICES = (
        (0, '发布者'),
        (1, '标注者'),
    )
    LEVEL_CHOICES = (
        (1, '等级1'),
        (2, '等级2'),
        (3, '等级3'),
        (4, '等级4'),
        (5, '等级5')
    )
    GENDER_CHOICES = (
        (1, '男'),
        (2, '女')
    )
    userID = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    permission = models.PositiveSmallIntegerField(choices=PERMISSION_CHOICES)
    level = models.IntegerField(choices=LEVEL_CHOICES, default=1)
    status = models.CharField(max_length=50, blank=True)
    gender = models.IntegerField(blank=True, null= True,choices=GENDER_CHOICES)
    email = models.EmailField()
    phone = models.CharField(max_length=11, blank=True)
    password = models.CharField(max_length=512)
    resumePath = models.TextField(blank=True)
    approvalResult = models.CharField(max_length=20, blank=True)
    headSculpturePath = models.CharField(max_length=200, default="static/images/ico_uer.gif")

class Task(models.Model):
    taskId = models.AutoField(primary_key=True) #任务id
    taskTitle = models.CharField(max_length=200, default=None) #任务名称
    taskDescription = models.TextField() #任务描述
    taskNumber = models.IntegerField(default=1) #任务数量
    taskRemainingNumber = models.IntegerField(default=None) #剩余任务数量
    taskRank = models.IntegerField() #需要匹配的标注者最低等级
    taskTypesChoices = (
        (0, '文本'),
        (1, '图像'),
        (2, '音频'),
    )
    taskType = models.PositiveSmallIntegerField(choices=taskTypesChoices, default=0) #任务类型
    perTaskPaid = models.DecimalField(max_digits=10, decimal_places=2) #一单位任务报酬
    createTime = models.DateTimeField(blank=True) #任务创建时间
    userID = models.ForeignKey(User, to_field='userID', on_delete=models.CASCADE) #发布任务的用户id
    task_status = models.CharField(max_length=50, default="已发布", null=False)
    modifyTime = models.DateTimeField(blank=True, null=True) #任务修改时间

class Order(models.Model):
    ORDER_STATES = (
        (0, '进行中'),
        (1, '已完成'),
        (2, '已取消'),
        (3, '申诉中'),
    )

    PAY_METHODS = (
        (0, '未支付'),
        (1, '支付宝'),
        (2, '微信'),
    )

    order_id = models.CharField(max_length=20, unique=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    publisher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='published_orders')
    labeler = models.ForeignKey(User, on_delete=models.CASCADE, related_name='labeled_orders')
    order_state = models.IntegerField(choices=ORDER_STATES)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    create_time = models.DateTimeField(auto_now_add=True)
    submit_time = models.DateTimeField(null=True, blank=True)
    pay_method = models.IntegerField(choices=PAY_METHODS)
    result_path = models.CharField(max_length=1024)
    dataset_path = models.CharField(max_length=1024)

djangoProject/PersonCenter/models.py
from django.db import models

# Create your models here.

djangoProject/PersonCenter/views.py
from django.shortcuts import render
from django.http import JsonResponse
from DataAnnodationSystem.models import User
import bcrypt
import os
from djangoProject import settings

def get_username(request):
    if request.method == 'GET':
        user_id = request.GET.get('userId')
        if user_id:
            try:
                user = User.objects.get(userID=user_id)
                username = user.name
                return JsonResponse({'username': username})
            except User.DoesNotExist:
                return JsonResponse({'error': 'User not found'}, status=404)
        else:
            return JsonResponse({'error': 'User ID not provided'}, status=400)
    else:
        return JsonResponse({'error': 'Method not allowed'}, status=405)

def get_headSculpturePath(request):
    if request.method == 'GET':
        user_id = request.GET.get('userId')
        if user_id:
            try:
                user = User.objects.get(userID=user_id)
                headSculpturePath = user.headSculpturePath
                return JsonResponse({'headSculpturePath': headSculpturePath})
            except User.DoesNotExist:
                return JsonResponse({'error': 'User not found'}, status=404)
        else:
            return JsonResponse({'error': 'User ID not provided'}, status=400)
    else:
        return JsonResponse({'error': 'Method not allowed'}, status=405)

def uploadAvatar(request):
    if request.method == 'POST':
        user_id = request.POST.get('userId')
        file = request.FILES.get('avatar')

        if not user_id or not file:
            return JsonResponse({'success': False, 'error': 'Missing user ID or file'})

        user = User.objects.get(userID=user_id)

        if not user:
            return JsonResponse({'success': False, 'error': 'User not found'})

        path = user.headSculpturePath
        if path and path != 'static/images/ico_uer.gif':
            path = os.path.normpath(path)
            oldPath = os.path.join(settings.MEDIA_ROOT, path)
            os.remove(oldPath)

        upload_dir = os.path.join(settings.MEDIA_ROOT, 'headSculpture')
        if not os.path.exists(upload_dir):
            os.makedirs(upload_dir)

        file_path = os.path.join(upload_dir, file.name)
        with open(file_path, 'wb+') as destination:
            for chunk in file.chunks():
                destination.write(chunk)

        relative_path = f'headSculpture/{file.name}'
        user.headSculpturePath = relative_path
        user.save()

        return JsonResponse({'success': True, 'path': relative_path})
def personCenter(request):
    return render(request, 'personCenter.html')

def personDetail(request):
    if request.method == 'GET':
        user_id = request.GET.get('userId')
        if user_id:
            try:
                user = User.objects.get(userID=user_id)
                if user.gender == 1:
                    gender = "male"
                elif user.gender == 2:
                    gender = "female"
                else:
                    gender = ""
                user_data = {
                    'userID': user.userID,
                    'name': user.name,
                    'phone': user.phone,
                    'email': user.email,
                    'gender': gender,
                    'level': user.level
                }

                return JsonResponse({'user': user_data})
            except User.DoesNotExist:
                return JsonResponse({'error': 'User not found'}, status=404)
        else:
            return JsonResponse({'error': 'User ID not provided'}, status=400)

    if request.method == 'POST':
        user_id = request.GET.get('userId')
        if user_id:
            try:
                user = User.objects.get(userID=user_id)
                # 更新用户信息
                user.name = request.POST.get('nickname')
                user.phone = request.POST.get('phone')
                user.email = request.POST.get('email')
                if request.POST.get('gender') == 'male':
                    user.gender = 1
                elif request.POST.get('gender') == 'female':
                    user.gender = 2
                user.save()  # 保存更新后的用户信息
                return JsonResponse({'success': True, 'message': 'User info updated successfully'})
            except User.DoesNotExist:
                return JsonResponse({'error': 'User not found'}, status=404)
        else:
            return JsonResponse({'error': 'User ID not provided'}, status=400)

def changePassword(request):
    if request.method == 'POST':
        try:
            user_id = request.GET.get('userId')
            old_password = request.POST.get('oldPassword')
            new_password = request.POST.get('newPassword')

            # 查询用户
            try:
                user = User.objects.get(userID=user_id)
            except User.DoesNotExist:
                return JsonResponse({'success': False, 'message': '用户不存在'})

            if not bcrypt.checkpw(old_password.encode('utf-8'), user.password.encode('utf-8')):
                return JsonResponse({'success': False, 'message': '旧密码错误'})

            # 修改密码
            hashed_new_password = bcrypt.hashpw(new_password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
            user.password = hashed_new_password
            user.save()

            return JsonResponse({'success': True, 'message': '密码修改成功'})
        except Exception as e:
            return JsonResponse({'success': False, 'message': str(e)})

    return JsonResponse({'success': False, 'message': '只支持POST请求'})

def deleteUser(request):
    if request.method == 'POST':
        user_id = request.GET.get('userId')
        try:
            user = User.objects.get(userID=user_id)
            user.delete()
            return JsonResponse({'success': True, 'message': '用户注销成功'})
        except User.DoesNotExist:
            return JsonResponse({'success': False, 'message': '用户不存在'})
    else:
        return JsonResponse({'success': False, 'message': '请求方法错误'})

djangoProject/templates/base.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>SentimentTagger</title>
<!--IE兼容组件-->
<meta name="keywords" content="{{project_name}}" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<link rel="icon" href="/static/img/favicon.ico" type="image/x-icon" />

<link href="/static/css/bootstrap.min.css" rel="stylesheet"> 
<link href="/static/css/docs.min.css" rel="stylesheet"> 
<!-- <script src="/static/js/bootstrap.min.js"></script> -->
<script src="/static/js/vue.min.js"></script>
<script src="/static/js/axios.min.js"></script>
</head>
<body>

<!-- 导航栏 -->
<header class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar">
  

  <div class="navbar-nav-scroll">
    <ul class="navbar-nav bd-navbar-nav flex-row">
      <li class="nav-item"><a class="nav-link active" href="/AnnotationMethod/hello/">SentimentTagger</a></li>
      <li class="nav-item"><a class="nav-link " href="/AnnotationMethod/help/">使用帮助</a></li> 
      <li class="nav-item"><a class="nav-link " href="/task/homepageforannotator/">返回标注者页面</a></li>
      <li class="nav-item"><a class="nav-link " href="/AnnotationMethod/download/">下载我的数据集</a></li>
    </ul>
  </div>
</header>

{% block content %}
{% endblock content %}

</body>
</html>

djangoProject/templates/hello.html
{% extends 'base.html' %}
{% block content %}
<!-- 主要内容 -->
<main class="bd-masthead" id="content" role="main">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-6 mx-auto col-md-6 order-md-2"> <img class="img-fluid mb-3 mb-md-0" src="/static/img/logo.png" alt="" width="1024" height="860"> </div>
      <div class="col-md-6 order-md-1 text-center text-md-left pr-md-5">
        <h1 class="mb-3 bd-text-purple-bright">SentimentTagger</h1>
        <p class="lead"> SentimentTagger 是一个超轻量级的开源文本标注工具，专门用于人工辅助标注的情感分类任务。</p>
        <p class="lead mb-4"> SentimentTagger 的前端页面主要基于 HTML，利用我们提供的反馈式标注工具，能够快速为你的想法开发出原型数据集，并迭代式的优化后端的标注结果。 </p>
	<div class="row mx-n2">
          <div class="col-md px-2">
            <a href="/AnnotationMethod/upload/" class="btn btn-lg btn-bd-primary w-100 mb-3" onclick="ga('Get started');">开始标注</a>
          </div>
          <div class="col-md px-2">
            <a href="/AnnotationMethod/info/" class="btn btn-lg btn-outline-secondary w-100 mb-3" onclick="ga('Get started');">有关内容</a>
          </div>
        </div>
        <p class="text-muted mb-0"> 当前版本：v0.0.1</p>
      </div>
    </div>
  </div>

</main>


<!-- 脚注信息 -->
<footer class="bd-footer text-muted">
  <div class="container-fluid p-3 p-md-5">
    <ul class="bd-footer-links">
      <li><a href="https://github.com/EINDICE">GitHub</a></li>
      <li><a href="/AnnotationMethod/help/">About</a></li>
    </ul>
    <p>Designed by <a href="https://github.com/EINDICE">Zhao</a> @Beihang Univ. Maintained by our team members.</p>
    <p><a href="https://mit-license.org/" target="_blank" rel="license noopener">MITrigger</a> license, <a
        href="https://creativecommons.org/licenses/by/3.0/" target="_blank" rel="license noopener">CC BY
        3.0</a>.</p>
  </div>
</footer>

{% endblock content %}

djangoProject/templates/help.html
{% extends 'base.html' %}
{% block content %}
<!-- 主要内容 -->
<main class="bd-masthead" id="content" role="main">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-6 mx-auto col-md-6 order-md-2"> <img class="img-fluid mb-3 mb-md-0" src="/static/img/logo.png" alt="" width="1024" height="860"> </div>
      <div class="col-md-6 order-md-1 text-center text-md-left pr-md-5">
        <h1 class="mb-3 bd-text-purple-bright">coming soon </h1> 
        <p>作者太忙(懒)，没时间写文档</p>
      </div>
    </div>
  </div>

</main>



<!-- 脚注信息 -->
<footer class="bd-footer text-muted">
  <div class="container-fluid p-3 p-md-5">
    <ul class="bd-footer-links">
      <li><a href="https://github.com/EINDICE">GitHub</a></li>
      <li><a href="/AnnotationMethod/help/">About</a></li>
    </ul>
    <p>Designed by <a href="https://github.com/EINDICE">Zhao</a> @Beihang Univ. Maintained by our team members.</p>
    <p><a href="https://mit-license.org/" target="_blank" rel="license noopener">MITrigger</a> license, <a
        href="https://creativecommons.org/licenses/by/3.0/" target="_blank" rel="license noopener">CC BY
        3.0</a>.</p>
  </div>
</footer>

{% endblock content %}

djangoProject/templates/info.html
{% extends 'base.html' %}
{% block content %}
<!-- 主要内容 -->
<main class="bd-masthead" id="content" role="main">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-6 mx-auto col-md-6 order-md-2"> <img class="img-fluid mb-3 mb-md-0"
                    src="/static/img/logo.png" alt="" width="1024" height="860"> </div>
            <div class="col-md-6 order-md-1 text-center text-md-left pr-md-5">
                <h1 class="mb-3 bd-text-purple-bright">有关SentimentTagger</h1>
                <p class="lead"> 文本情感分类标注工具</p>
                <p class="lead mb-4"> 可用于通用场景、金融、医疗等NLP情感分析任务 </p>
                <p class="text-muted mb-0"> 当前版本：0.0.1</p>
            </div>
        </div>
    </div>

</main>


<!-- 脚注信息 -->
<footer class="bd-footer text-muted">
    <div class="container-fluid p-3 p-md-5">
        <ul class="bd-footer-links">
            <li><a href="https://github.com/EINDICE">GitHub</a></li>
            <li><a href="/AnnotationMethod/help/">About</a></li>
        </ul>
        <p>Designed by <a href="https://github.com/EINDICE">Zhao</a> @Beihang Univ. Maintained by our team members.</p>
        <p><a href="https://mit-license.org/" target="_blank" rel="license noopener">MITrigger</a> license, <a
                href="https://creativecommons.org/licenses/by/3.0/" target="_blank" rel="license noopener">CC BY
                3.0</a>.</p>
    </div>
</footer>

{% endblock content %}

djangoProject/templates/标注者-任务列表.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- <link rel="stylesheet" href="css/amazeui.min.css" />  -->
    <!-- <link rel="stylesheet" href="css/admin.css" />  -->
    
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <link rel="stylesheet" href="/static/css/project.css">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <script src="/static/layui/layui.js"></script>
    <style>
        .layui-form-label {
            width: 100px;
        }
    
        .layui-table-view {
            margin-left: 70px;
        }
    
        hr {
            margin: 10px auto;
        }
    
        .form-control {
            height: 30px;
            font-size: small;
        }
    
        .btn {
            padding: 3px 10px;
        }
    
        #type {
            color: #999;
        }
    
        #type option {
            color: #555;
        }
    
        .layui-btn {
            padding: 0px 3px;
            height: 30px;
            line-height: 30px;
            font-size: 12px;
        }

        .user-img img { width: 40px; height: 40px; border-radius: 50%; }

        #dropdownMenu {
            display: none;
            position: absolute;
            right: 0;
            background-color: white;
            border: 1px solid #ccc;
            padding: 10px;
            white-space: nowrap;
        }

        #dropdownMenu a {
            display: block;
            padding: 5px 3px;
            color: black;
            text-decoration: none;
        }

        #dropdownMenu a:hover {
            background-color: #f1f1f1;
        }

        /* CSS for the avatar dialog */
        #avatarDialog {
            display: none;
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background-color: #fff;
            border: 1px solid black;
            padding: 40px; /* Increased padding for larger dialog */
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            z-index: 9999; /* Ensure dialog is on top of other elements */
            width: 400px; /* Set a fixed width */
        }

        #avatarPreview {
            text-align: center;
            margin-bottom: 20px;
            height: 200px; /* Fixed height */
            display: flex;
            justify-content: center;
            align-items: center;
        }

        #avatarPreview img {
            max-width: 100%; /* Image should not exceed the container width */
            max-height: 100%; /* Image should not exceed the container height */
            border-radius: 50%;
        }

        #avatarDialog .file-select, #avatarDialog button {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            display: inline-block; /* Align buttons inline */
            margin: 10px; /* Space between buttons */
        }

        #avatarDialog .file-select {
            margin-left: auto; /* Align the label button to the left */
        }

        #avatarDialog button {
            margin-right: auto; /* Align the button to the right */
        }

        #avatarInput {
            display: none; /* Hide the file input */
        }
    </style>
    <title>任务申领</title>
</head>

<body>
    <!-- 顶部 -->
    <header>
        <div id="Header">
            <div id="head">
                <div class="tit">机器学习数据标注平台| 标注者端</div>
                <ul id="Navi">
                    <li><a href="/task/homepageforannotator/"><span>平台主页</span></a></li>
                    <li><a href="/task/task_list/"><span>任务申领</span></a></li>
                    <li><a href="/OrderManage/BiaozhuzheOrderList/"><span>我的订单</span></a></li>
                    <!--<li><a href="/annotator/pay"><span>薪酬管理</span></a></li>     --> 
                    <li><a href="/personCenter/personCenter/"><span>个人中心</span></a></li>
                    <li><a href="/AnnotationMethod/hello"><span>标注工具</span></a></li>
                </ul>
                <div class="user-img" style="cursor: pointer;" onclick="showAvatarDialog()">
                    <img src="" alt="User Avatar" id="userAvatar">
                </div>

                 <div id="avatarDialog">
                    <div id="avatarPreview"></div>
                    <label for="avatarInput" class="file-select" style="background-color: #2f4056; color: #fff; padding: 10px 20px; border-radius: 5px; cursor: pointer; display: inline-block; margin-right: 10px;">选择图片</label>
                    <input type="file" id="avatarInput" accept="image/*" onchange="previewAvatar()" style="display: none;">
                    <button onclick="uploadAvatar()" style="background-color: #ffb800; color: #fff; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer; display: inline-block;">确认更换</button>
                </div>

                <div class="user" style="position: absolute;top: 0px;right: 1%;font-size: 20px;">
                    <label for="menu" style="font-size: 14px;font-weight: normal;color: #000;"><span id="username"></span></label>
                    <button type="button" class="user-set" id="menu" style="display: inline-block;">
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </button>
                    <div id="dropdownMenu" style="display: none; position: absolute; right: 0; background-color: white; border: 1px solid #ccc; padding: 10px;">
                        <a href="/index" onclick="document.cookie = 'user=;expires=Thu, 01 Jan 1970 00:00:00 UTC;'">退出登录</a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="text-center">
        <h1><br><br><br><strong>任务列表</strong></h1>
        <!-- 跳转到搜索页面的按钮 -->
        <a href="{% url 'search_tasks' %}" class="btn btn-primary">我要搜索</a><br>
        {% for task in tasks %}
        <div>
            <h3><a href="{% url 'task_detail' task_id=task.taskId %}">{{ task.taskTitle }}</a></h2>
            <p>任务类型: {{ task.get_taskType_display }}</p>
        </div>
        {% empty %}
        <p>暂无任务</p>
        {% endfor %}

    </div>
    
    
    <br><br><br><br><br><div class="text-center">
        <!-- 分页链接 -->
        {% if tasks.has_previous %}
        <a href="?page=1">首页</a>
        <a href="?page={{ tasks.previous_page_number }}">上一页</a>
        {% endif %}
        
        <span>页码: {{ tasks.number }} / {{ tasks.paginator.num_pages }}</span>
        
        {% if tasks.has_next %}
        <a href="?page={{ tasks.next_page_number }}">下一页</a>
        <a href="?page={{ tasks.paginator.num_pages }}">尾页</a>
        {% endif %}
    </div>

    <script>
        // 从sessionStorage中获取用户ID
        const userId = sessionStorage.getItem('userId');

        // 发送请求到后端获取用户名
        fetch(`/personCenter/getUserName/?userId=${userId}`)
            .then(response => response.json())
            .then(data => {
                const username = data.username;
                // 更新页面上的用户名显示
                document.getElementById('username').textContent = username;
            })
            .catch(error => console.error('Error:', error));

        // 发送请求到后端获取头像路径
        fetch(`/personCenter/getHeadSculpturePath/?userId=${userId}`)
            .then(response => response.json())
            .then(data => {
                let headSculpturePath = data.headSculpturePath;
                if (headSculpturePath === 'static/images/ico_uer.gif') {
                    document.getElementById('userAvatar').src = '/static/images/ico_uer.gif';
                }else{
                    document.getElementById('userAvatar').src = `/media/${headSculpturePath}`;
                }
            })
            .catch(error => console.error('Error:', error));

        document.getElementById('menu').addEventListener('click', function() {
            var dropdownMenu = document.getElementById('dropdownMenu');
            if (dropdownMenu.style.display === 'none' || dropdownMenu.style.display === '') {
                dropdownMenu.style.display = 'block';
            } else {
                dropdownMenu.style.display = 'none';
            }
        });

        // 移除旧的事件监听器
        document.removeEventListener('click', avatarDialogClickListener);

        // 添加新的事件监听器
        document.addEventListener('click', avatarDialogClickListener);

        // 新的事件监听器
        function avatarDialogClickListener(event) {
            var dropdownMenu = document.getElementById('dropdownMenu');
            var menuButton = document.getElementById('menu');
            var avatarDialog = document.getElementById('avatarDialog');
            var userImg = document.querySelector('.user-img');

            // 检查点击的目标是否是下拉菜单以外的区域
            if (dropdownMenu.style.display === 'block' && !menuButton.contains(event.target) && !dropdownMenu.contains(event.target)) {
                dropdownMenu.style.display = 'none';
            }

            // 检查点击的目标是否是头像框以外的区域
            if (avatarDialog.style.display === 'block' && !avatarDialog.contains(event.target) && event.target !== userImg) {
                avatarDialog.style.display = 'none';
            }
        }

        document.querySelector('.user-img').addEventListener('click', function(event) {
            showAvatarDialog();
            event.stopPropagation();  // 阻止事件冒泡
        });

        function showAvatarDialog() {
            const userAvatarSrc = document.getElementById('userAvatar').src;
            document.getElementById('avatarPreview').innerHTML = `<img src="${userAvatarSrc}" alt="Avatar Preview">`;
            document.getElementById('avatarDialog').style.display = 'block';
        }

        function previewAvatar() {
            const preview = document.getElementById('avatarPreview');
            const file = document.getElementById('avatarInput').files[0];
            const reader = new FileReader();

            reader.onloadend = function () {
                preview.innerHTML = `<img src="${reader.result}" alt="Avatar Preview">`;
            };

            if (file) {
                reader.readAsDataURL(file);
            } else {
                preview.innerHTML = "";
            }
        }

        function uploadAvatar() {
            const file = document.getElementById('avatarInput').files[0];
            if (file) {
                const formData = new FormData();
                formData.append('avatar', file);
                formData.append('userId', userId);

                fetch('/personCenter/uploadAvatar/', {
                    method: 'POST',
                    body: formData
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        document.getElementById('userAvatar').src = URL.createObjectURL(file);
                        document.getElementById('avatarDialog').style.display = 'none';
                    } else {
                        alert('Failed to upload avatar');
                    }
                })
                .catch(error => console.error('Error:', error));
            } else {
                alert("Please select an image to upload.");
            }
        }
    </script>
</body>

</html>